"""The interface every spacetime implements.

A metric is a set of Numba-compiled *kernels*: functions of a position ``x = (t, r, theta, phi)``,
a float64 array of shape ``(4,)``, that return full arrays. The index conventions are fixed here
and used throughout the package (``docs/decisions/0004-metric-interface.md``):

==================  ============  ==========================================================
kernel              shape         entry ``[i, j, k]``
==================  ============  ==========================================================
``g(x)``            ``(4, 4)``    ``g_{ij}``
``g_inv(x)``        ``(4, 4)``    ``g^{ij}``
``dg_inv(x)``       ``(4, 4, 4)`` ``d_i g^{jk}``: the derivative index comes first
``christoffel(x)``  ``(4, 4, 4)`` ``Gamma^i_{jk}``: the upper index comes first
``invariants(x,p)`` ``(n,)``      constants of motion, in the order of ``invariant_names``
==================  ============  ==========================================================

No kernel and no caller may assume that the metric is diagonal: formulations contract over every
index pair, so that Kerr (``g^{t phi} != 0``) needs a new metric but no new formulation code.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import NamedTuple

import numpy as np
from numpy.typing import NDArray

Kernel = Callable[..., NDArray[np.float64]]


class MetricKernels(NamedTuple):
    """The compiled functions that define a metric (index conventions in the module docstring)."""

    g: Kernel
    g_inv: Kernel
    dg_inv: Kernel
    christoffel: Kernel
    invariants: Kernel


@dataclass(frozen=True)
class StopSurface:
    """A coordinate surface at which an integration must terminate.

    The integration stops when coordinate ``index`` reaches ``value`` while moving in
    ``direction`` (``-1``: decreasing, ``+1``: increasing). ``name`` becomes the status of the
    solution, for example ``"captured"``.
    """

    name: str
    index: int
    value: float
    direction: int


class Metric:
    """A spacetime: compiled kernels plus the metadata integrations and diagnostics need.

    Subclasses build their kernels (by hand, or generated by ``tools/derive_metric.py``), pass
    them to ``__init__``, set the class attributes and implement :attr:`horizon`.

    Attributes
    ----------
    g, g_inv, dg_inv, christoffel : kernel ``x -> array``
        See the module docstring for shapes and index order.
    invariants : kernel ``(x, p) -> array``
        Constants of motion that follow from the symmetries of the spacetime (Killing vectors
        and tensors), written in the canonical variables ``(x, p_mu)``. Formulation (a) lowers
        its velocity, ``p = g u``, before calling it.
    invariant_names : tuple of str
        Names of those constants, in kernel order, e.g. ``("E", "Lz", "L2")``.
    cyclic_coords : tuple of int
        Coordinates the metric does not depend on. The matching slices ``dg_inv(x)[mu]`` must be
        exact zeros, which makes ``p_mu`` conserved bit for bit in formulation (b) (theory §5.2).
    """

    invariant_names: tuple[str, ...] = ()
    cyclic_coords: tuple[int, ...] = ()

    def __init__(self, kernels: MetricKernels):
        self.kernels = kernels
        self.g = kernels.g
        self.g_inv = kernels.g_inv
        self.dg_inv = kernels.dg_inv
        self.christoffel = kernels.christoffel
        self.invariants = kernels.invariants

    @property
    def horizon(self) -> float:
        """Coordinate radius of the (outer) event horizon."""
        raise NotImplementedError

    def stop_surfaces(self, horizon_margin: float = 1e-3) -> tuple[StopSurface, ...]:
        """Surfaces where an integration must stop, by default ``r = r_h (1 + horizon_margin)``.

        Coordinate singularities make every integrator fail at the horizon (pitfall 1),
        so a geodesic that gets this close is reported as captured.
        """
        return (StopSurface("captured", 1, self.horizon * (1.0 + horizon_margin), -1),)
