"""Exact references for Schwarzschild geodesics (``M = 1``)."""

from .schwarzschild_deflection import (
    BOZZA_B,
    bozza_deflection,
    deflection_angle,
    deflection_darwin,
    delta_phi,
    delta_phi_quadrature,
    periapsis,
    turning_point_delta_phi,
    weak_field_deflection,
    windings,
)
from .schwarzschild_orbits import (
    B_CRIT,
    ISCO,
    LYAPUNOV_PHOTON_SPHERE,
    PHOTON_SPHERE,
    EccentricOrbit,
    EL_to_pe,
    circular_orbit_constants,
    circular_orbit_frequency,
    circular_orbit_period,
    pe_to_EL,
    separatrix,
)

__all__ = [
    "BOZZA_B",
    "B_CRIT",
    "ISCO",
    "LYAPUNOV_PHOTON_SPHERE",
    "PHOTON_SPHERE",
    "EL_to_pe",
    "EccentricOrbit",
    "bozza_deflection",
    "circular_orbit_constants",
    "circular_orbit_frequency",
    "circular_orbit_period",
    "deflection_angle",
    "deflection_darwin",
    "delta_phi",
    "delta_phi_quadrature",
    "pe_to_EL",
    "periapsis",
    "separatrix",
    "turning_point_delta_phi",
    "weak_field_deflection",
    "windings",
]
